runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()

filetype plugin on

let isWindowsHost = has('win32') || has('win16')

if !has('gui_running')
	colors wombat
	if !isWindowsHost
		set t_Co=256
	endif	
else
	colors herald
	set guioptions-=T
	if isWindowsHost
		set gfn=Ubuntu\ Mono:h11:cANSI
		set printfont=Ubuntu\ Mono:h10:cANSI
	else
		set gfn=Ubuntu\ Mono\ 11
		set printfont=Ubuntu\ Mono\ 10
	endif
endif	

if isWindowsHost
	set directory=$USERPROFILE\\vimfiles\\swp//,.,C:\temp//
else
	set directory=~/.vim/swp//,.,/tmp//
endif

if has("multi_byte")
  if &termencoding == ""
    let &termencoding = &encoding
  endif
  set encoding=utf-8
  setglobal fileencoding=utf-8
  "setglobal bomb
  set fileencodings=ucs-bom,utf-8,latin1
endif

set ai
set nu
set hlsearch
set incsearch
set cursorline
set cursorcolumn
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [ENC=%{strlen(&fenc)?&fenc:'none'}]\ [TYPE=%Y]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
set laststatus=2
set showcmd
set linebreak
set nowrap
set tabstop=2
set shiftwidth=2
set expandtab
set bg=dark
syntax on

" Filetypes
au BufRead,BufNewFile *.json set filetype=js
au BufRead,BufNewFile *.less set filetype=css
au BufRead,BufNewFile *.emd set filetype=markdown
au BufRead,BufNewFile *.emd.expected set filetype=lisp

if v:version >= 700
	set omnifunc=syntaxcomplete#Complete
	set completeopt=longest,menuone

	function! JSynPreceding()
		return synIDattr(synIDtrans(synID(line('.'), col('.') - 1, 1)), 'name')
	endfunction

	function! JSynFollowing()
		return synIDattr(synIDtrans(synID(line('.'), col('.'), 1)), 'name')
	endfunction

	" Comment Todo Constant String Identifier Function 
	" Type Statement Keyword PreProc Number Special
	function! PeriodComplete()
		if pumvisible()
			return '.'
		endif
	endfunction

	" CleverTab per http://vim.wikia.com/wiki/VimTip102
	function! CleverTab()
		if pumvisible()
			return "\<C-N>"
		endif
		if strpart( getline('.'), 0, col('.')-1 ) =~ '^\s*$'
			return "\<Tab>"
		elseif exists('&omnifunc') && &omnifunc != ''
			return "\<C-X>\<C-O>"
		else
			return "\<C-N>"
		endif
	endfunction
	" VsVim does not play well with this at all.
	"inoremap <Tab> <C-R>=CleverTab()<CR>
endif	
